version: "3.8"

services:    
  db:
    build: ./requirements/mariadb/.
    container_name: maria-cont
    image: mariadb:mytag
    restart: always
    networks:
      - app-network
    volumes:
      - mydata:/shard_data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u$$MY_USER", "-p$$MY_PASS"]
      interval: 10s
      timeout: 5s
      retries: 3


  wordpress:
    depends_on:
      db:
        condition: service_healthy
    build: ./requirements/wordpress/.
    container_name: wordpress-cont
    image: wordpress:mytag
    restart: always
    volumes:
      - mydata:/shard_data
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/.
    container_name: nginx-cont
    image: nginx:mytag
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - mydata:/shard_data 
    networks:
      - app-network

#volumes:
#  Wordpress:
#    name : wordpress
#  DataBase:
#    name : mariadb
volumes:
  mydata:
  
networks:
  app-network: