version: "3.8"

services:    
  db:
    build: ./requirements/mariadb/.
    container_name: maria-cont
    image: mariadb:mytag
    restart: always
    networks:
      - app-network
    volumes:
      - mydata:/shard_data

  wordpress:
    depends_on:
      - db
    build: ./requirements/wordpress/.
    container_name: wordpress-cont
    image: wordpress:mytag
    restart: always
    volumes:
      - mydata:/shard_data
    networks:
      - app-network

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx/.
    container_name: nginx-cont
    image: nginx:mytag
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - mydata:/shard_data 
    networks:
      - app-network

#volumes:
#  Wordpress:
#    name : wordpress
#  DataBase:
#    name : mariadb
volumes:
  mydata:
  
networks:
  app-network: